package ge.tbegvadze.toon3d.input.touch;

public enum TouchAction {
    FORWARD, BACK, ROTATE_LEFT, ROTATE_RIGHT, STRAFE_LEFT, STRAFE_RIGHT,
    FIRE, SKIP_TURN, RELOAD, SWITCH_WEAPON,
    HEAL, OPEN_INVENTORY, INSPECT_WEAPON, USE_MACHINE,
    NONE
}
