package ge.tbegvadze.toon3d.util;

/**
 * DEV-ONLY balance auditor. Prints the "living table" of every current weapon and enemy
 * with its computed Power Score / Threat Points, flags any content that falls OUTSIDE its
 * role band, and checks the golden ratio. This is the honest counterpart to the prose
 * contract in {@code docs/balance-rule-system.txt}: the numbers here come straight from
 * {@link BalanceConfig} through {@link GameMath}, so they cannot drift from the real game
 * values — when {@code BalanceConfig} changes, rerun this and regenerate the doc table.
 *
 * <p>This class is NOT part of the game loop. It touches no LibGDX render state and only
 * calls the pure contract formulas in {@link GameMath}, so it runs headless:
 * <pre>./gradlew core:run -PmainClass=ge.tbegvadze.toon3d.util.BalanceReport</pre>
 * (or run {@link #main(String[])} directly from an IDE). It exists purely to keep the
 * balance contract honest — the table can't lie.
 */
public final class BalanceReport {

    private BalanceReport() {}

    // Weapon roles and their power-score bands (from BalanceConfig).
    private enum WeaponRole {
        SIDEARM   (BalanceConfig.WEAPON_POWER_SIDEARM_MIN,   BalanceConfig.WEAPON_POWER_SIDEARM_MAX),
        WORKHORSE (BalanceConfig.WEAPON_POWER_WORKHORSE_MIN, BalanceConfig.WEAPON_POWER_WORKHORSE_MAX),
        BURST     (BalanceConfig.WEAPON_POWER_BURST_MIN,     BalanceConfig.WEAPON_POWER_BURST_MAX),
        HEAVY     (BalanceConfig.WEAPON_POWER_HEAVY_MIN,     BalanceConfig.WEAPON_POWER_HEAVY_MAX);

        final float bandMinimum;
        final float bandMaximum;

        WeaponRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    // Enemy roles and their threat-point bands (from BalanceConfig).
    private enum EnemyRole {
        CHAFF      (BalanceConfig.ENEMY_TP_CHAFF_MIN,      BalanceConfig.ENEMY_TP_CHAFF_MAX),
        SOLDIER    (BalanceConfig.ENEMY_TP_SOLDIER_MIN,    BalanceConfig.ENEMY_TP_SOLDIER_MAX),
        BRUISER    (BalanceConfig.ENEMY_TP_BRUISER_MIN,    BalanceConfig.ENEMY_TP_BRUISER_MAX),
        MINI_ELITE (BalanceConfig.ENEMY_TP_MINI_ELITE_MIN, BalanceConfig.ENEMY_TP_MINI_ELITE_MAX);

        final float bandMinimum;
        final float bandMaximum;

        EnemyRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    public static void main(String[] commandLineArguments) {
        printHeader();
        printWeaponTable();
        System.out.println();
        printEnemyTable();
        System.out.println();
        printLegend();
    }

    private static void printHeader() {
        System.out.println("====================================================================================");
        System.out.println(" toon3D BALANCE RULE SYSTEM — LIVING TABLE (generated by BalanceReport)");
        System.out.println(" Reference player DPT = " + BalanceConfig.REFERENCE_PLAYER_DPT
                + "   eHP = " + BalanceConfig.REFERENCE_PLAYER_EHP
                + "   ammoEff anchor = " + BalanceConfig.REFERENCE_AMMO_EFFICIENCY);
        System.out.println("====================================================================================");
    }

    // -----------------------------------------------------------------------------------
    // WEAPONS — sustained DPT, ammo efficiency, power score vs role band.
    // -----------------------------------------------------------------------------------
    private static void printWeaponTable() {
        System.out.println("WEAPONS");
        System.out.printf("%-16s %-10s %8s %8s %10s %12s %-6s%n",
                "weapon", "role", "sustDPT", "ammoEff", "powerScore", "band", "in?");
        System.out.println("------------------------------------------------------------------------------------");

        printWeaponRow("Shotgun",        WeaponRole.BURST,
                BalanceConfig.SHOTGUN_CLIP_SIZE,     BalanceConfig.SHOTGUN_DAMAGE,     BalanceConfig.SHOTGUN_RELOAD_TIME_TICKS,  1);
        printWeaponRow("Dbl Shotgun",    WeaponRole.BURST,
                BalanceConfig.DBL_SHOTGUN_CLIP_SIZE, BalanceConfig.DBL_SHOTGUN_DAMAGE, BalanceConfig.DBL_SHOTGUN_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Plasma Rifle",   WeaponRole.BURST,
                BalanceConfig.PLASMA_RIFLE_CLIP_SIZE, BalanceConfig.PLASMA_RIFLE_DAMAGE, BalanceConfig.PLASMA_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Assault Rifle",  WeaponRole.WORKHORSE,
                BalanceConfig.ASSAULT_RIFLE_CLIP_SIZE, BalanceConfig.ASSAULT_RIFLE_DAMAGE, BalanceConfig.ASSAULT_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Chaingun",       WeaponRole.WORKHORSE,
                BalanceConfig.CHAINGUN_CLIP_SIZE, BalanceConfig.CHAINGUN_DAMAGE, BalanceConfig.CHAINGUN_RELOAD_TIME_TICKS, 1);
        // Railgun scored at FULL charge (its intended engagement state).
        printWeaponRow("Railgun(full)",  WeaponRole.HEAVY,
                BalanceConfig.RAILGUN_CLIP_SIZE,
                BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE[BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE.length - 1],
                BalanceConfig.RAILGUN_RELOAD_TIME_TICKS, 1);
        // Grenade scored on its centre splash damage.
        printWeaponRow("Grenade Lchr",   WeaponRole.HEAVY,
                BalanceConfig.GRENADE_CLIP_SIZE, BalanceConfig.GRENADE_SPLASH_DAMAGE, BalanceConfig.GRENADE_RELOAD_TIME_TICKS, 1);
    }

    private static void printWeaponRow(String weaponName, WeaponRole weaponRole,
                                       int clipSize, int damagePerShot, int reloadTicks, int ammoPerShot) {
        float sustainedDamagePerTurn = GameMath.sustainedDamagePerTurn(clipSize, damagePerShot, reloadTicks);
        float ammoEfficiency = GameMath.ammoEfficiency(damagePerShot, ammoPerShot);
        float ammoEfficiencyNormalized = ammoEfficiency / BalanceConfig.REFERENCE_AMMO_EFFICIENCY;
        float powerScore = GameMath.weaponPowerScore(sustainedDamagePerTurn, ammoEfficiencyNormalized);

        boolean insideBand = powerScore >= weaponRole.bandMinimum && powerScore <= weaponRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", weaponRole.bandMinimum, weaponRole.bandMaximum);

        System.out.printf("%-16s %-10s %8.1f %8.1f %10.1f %12s %-6s%n",
                weaponName, weaponRole.name(), sustainedDamagePerTurn, ammoEfficiency,
                powerScore, bandText, bandVerdict(insideBand, powerScore, weaponRole.bandMinimum));
    }

    // -----------------------------------------------------------------------------------
    // ENEMIES — threat points vs role band, plus the golden-ratio (TTD/TTK) sanity check.
    // Golden ratio uses the player's best burst (shotgun) for TTK and reference eHP for TTD.
    // -----------------------------------------------------------------------------------
    private static void printEnemyTable() {
        System.out.println("ENEMIES");
        System.out.printf("%-16s %-11s %5s %6s %5s %8s %10s %-6s %9s %-6s%n",
                "enemy", "role", "eHP", "atkDmg", "cad", "posMult", "TP", "in?", "TTD/TTK", "gr?");
        System.out.println("------------------------------------------------------------------------------------");

        // cadence: ranged enemies attack every turn (1); melee enemies attack on their move cadence.
        printEnemyRow("Gore Biter",  EnemyRole.CHAFF,   BalanceConfig.GORE_BITER_MAX_HEALTH,
                BalanceConfig.GORE_BITER_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Eye Tyrant",  EnemyRole.CHAFF,   BalanceConfig.EYE_TYRANT_MAX_HEALTH,
                BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Acid Drone",  EnemyRole.SOLDIER, BalanceConfig.ACID_DRONE_MAX_HEALTH,
                BalanceConfig.ACID_DRONE_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Void Shroud", EnemyRole.SOLDIER, BalanceConfig.VOID_SHROUD_MAX_HEALTH,
                BalanceConfig.VOID_SHROUD_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Mire Wraith", EnemyRole.SOLDIER, BalanceConfig.MIRE_WRAITH_MAX_HEALTH,
                BalanceConfig.MIRE_WRAITH_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Shell Brute", EnemyRole.BRUISER, BalanceConfig.SHELL_BRUTE_MAX_HEALTH,
                BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_MELEE,      true);
        printEnemyRow("Plague Hulk", EnemyRole.SOLDIER, BalanceConfig.PLAGUE_HULK_MAX_HEALTH,
                BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE, BalanceConfig.PLAGUE_HULK_MOVE_EVERY_N_TURNS,
                BalanceConfig.POSITIONAL_MULT_MELEE,      false);
        // Iron Stalker scored on its melee profile (its higher damage line), like the contract worked example.
        printEnemyRow("Iron Stalker", EnemyRole.MINI_ELITE, BalanceConfig.IRON_STALKER_MAX_HEALTH,
                BalanceConfig.IRON_STALKER_MELEE_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, true);
    }

    private static void printEnemyRow(String enemyName, EnemyRole enemyRole, int rawHealth,
                                      int attackDamage, int attackCadenceTurns,
                                      float positionalMultiplier, boolean useBruiserGoldenBand) {
        // Enemies currently have no dodge or flat reduction, so eHP == raw HP.
        float enemyEffectiveHitPoints = GameMath.effectiveHitPoints(rawHealth, 0f, 0f, 0f, 0f);
        float threatPoints = GameMath.threatPoints(attackDamage, attackCadenceTurns,
                enemyEffectiveHitPoints, BalanceConfig.REFERENCE_PLAYER_DPT, positionalMultiplier);
        boolean insideBand = threatPoints >= enemyRole.bandMinimum && threatPoints <= enemyRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", enemyRole.bandMinimum, enemyRole.bandMaximum);

        // Golden ratio: TTK by the player's best burst (shotgun), TTD by enemy DPT into reference eHP.
        int turnsToKill = GameMath.turnsToKill(enemyEffectiveHitPoints, BalanceConfig.SHOTGUN_DAMAGE);
        float enemyDamagePerTurn = (float) attackDamage / Math.max(1, attackCadenceTurns);
        int turnsToDie = GameMath.turnsToKill(BalanceConfig.REFERENCE_PLAYER_EHP, enemyDamagePerTurn);
        float goldenRatio = GameMath.goldenRatio(turnsToDie, turnsToKill);

        float goldenMinimum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MIN : BalanceConfig.GOLDEN_RATIO_TRASH_MIN;
        float goldenMaximum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MAX : BalanceConfig.GOLDEN_RATIO_TRASH_MAX;
        boolean goldenInside = goldenRatio >= goldenMinimum && goldenRatio <= goldenMaximum;

        System.out.printf("%-16s %-11s %5.0f %6d %5d %8.2f %10.1f %-6s %9.1f %-6s%n",
                enemyName, enemyRole.name(), enemyEffectiveHitPoints, attackDamage, attackCadenceTurns,
                positionalMultiplier, threatPoints, bandVerdict(insideBand, threatPoints, enemyRole.bandMinimum),
                goldenRatio, bandVerdict(goldenInside, goldenRatio, goldenMinimum));
    }

    private static String bandVerdict(boolean insideBand, float value, float bandMinimum) {
        if (insideBand) {
            return "OK";
        }
        return value < bandMinimum ? "UNDER" : "OVER";
    }

    private static void printLegend() {
        System.out.println("LEGEND: in?/gr? = OK inside band, UNDER below band, OVER above band.");
        System.out.println("  sustDPT = (clip*dmg)/(clip+reload).  powerScore = sustDPT*sqrt(ammoEff/anchor).");
        System.out.println("  TP = (atkDmg/cadence) * (eHP/refDPT) * posMult.  TTD/TTK = golden ratio.");
        System.out.println("Out-of-band rows are tuning targets — see docs/balance-rule-system.txt.");
    }
}
