package ge.tbegvadze.toon3d.util;

/**
 * DEV-ONLY balance auditor. Prints the "living table" of every current weapon and enemy
 * with its computed Power Score / Threat Points, flags any content that falls OUTSIDE its
 * role band, and checks the golden ratio. This is the honest counterpart to the prose
 * contract in {@code docs/balance-rule-system.txt}: the numbers here come straight from
 * {@link BalanceConfig} through {@link GameMath}, so they cannot drift from the real game
 * values — when {@code BalanceConfig} changes, rerun this and regenerate the doc table.
 *
 * <p>This class is NOT part of the game loop. It touches no LibGDX render state and only
 * calls the pure contract formulas in {@link GameMath}, so it runs headless:
 * <pre>./gradlew core:run -PmainClass=ge.tbegvadze.toon3d.util.BalanceReport</pre>
 * (or run {@link #main(String[])} directly from an IDE). It exists purely to keep the
 * balance contract honest — the table can't lie.
 */
public final class BalanceReport {

    private BalanceReport() {}

    // Weapon roles and their power-score bands (from BalanceConfig).
    private enum WeaponRole {
        SIDEARM   (BalanceConfig.WEAPON_POWER_SIDEARM_MIN,   BalanceConfig.WEAPON_POWER_SIDEARM_MAX),
        WORKHORSE (BalanceConfig.WEAPON_POWER_WORKHORSE_MIN, BalanceConfig.WEAPON_POWER_WORKHORSE_MAX),
        BURST     (BalanceConfig.WEAPON_POWER_BURST_MIN,     BalanceConfig.WEAPON_POWER_BURST_MAX),
        HEAVY     (BalanceConfig.WEAPON_POWER_HEAVY_MIN,     BalanceConfig.WEAPON_POWER_HEAVY_MAX);

        final float bandMinimum;
        final float bandMaximum;

        WeaponRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    // Enemy roles and their threat-point bands (from BalanceConfig).
    private enum EnemyRole {
        CHAFF      (BalanceConfig.ENEMY_TP_CHAFF_MIN,      BalanceConfig.ENEMY_TP_CHAFF_MAX),
        SOLDIER    (BalanceConfig.ENEMY_TP_SOLDIER_MIN,    BalanceConfig.ENEMY_TP_SOLDIER_MAX),
        BRUISER    (BalanceConfig.ENEMY_TP_BRUISER_MIN,    BalanceConfig.ENEMY_TP_BRUISER_MAX),
        MINI_ELITE (BalanceConfig.ENEMY_TP_MINI_ELITE_MIN, BalanceConfig.ENEMY_TP_MINI_ELITE_MAX);

        final float bandMinimum;
        final float bandMaximum;

        EnemyRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    public static void main(String[] commandLineArguments) {
        printHeader();
        printWeaponTable();
        System.out.println();
        printEnemyTable();
        System.out.println();
        printBlockTable();
        System.out.println();
        printMoveSetTable();
        System.out.println();
        printUpgradeCardTable();
        System.out.println();
        printScarcityTable();
        System.out.println();
        printEncounterTable();
        System.out.println();
        printDepthCouplingTable();
        System.out.println();
        printHazardTable();
        System.out.println();
        printTelegraphAudit();
        System.out.println();
        printBossRulesetTable();
        System.out.println();
        printLegend();
    }

    private static void printHeader() {
        System.out.println("====================================================================================");
        System.out.println(" toon3D BALANCE RULE SYSTEM — LIVING TABLE (generated by BalanceReport)");
        System.out.println(" Reference player DPT = " + BalanceConfig.REFERENCE_PLAYER_DPT
                + "   eHP = " + BalanceConfig.REFERENCE_PLAYER_EHP
                + "   ammoEff anchor = " + BalanceConfig.REFERENCE_AMMO_EFFICIENCY);
        System.out.println("====================================================================================");
    }

    // -----------------------------------------------------------------------------------
    // WEAPONS — sustained DPT, ammo efficiency, power score vs role band.
    // -----------------------------------------------------------------------------------
    private static void printWeaponTable() {
        System.out.println("WEAPONS");
        System.out.printf("%-16s %-10s %8s %8s %10s %12s %-6s%n",
                "weapon", "role", "sustDPT", "ammoEff", "powerScore", "band", "in?");
        System.out.println("------------------------------------------------------------------------------------");

        printWeaponRow("Shotgun",        WeaponRole.BURST,
                BalanceConfig.SHOTGUN_CLIP_SIZE,     BalanceConfig.SHOTGUN_DAMAGE,     BalanceConfig.SHOTGUN_RELOAD_TIME_TICKS,  1);
        printWeaponRow("Dbl Shotgun",    WeaponRole.BURST,
                BalanceConfig.DBL_SHOTGUN_CLIP_SIZE, BalanceConfig.DBL_SHOTGUN_DAMAGE, BalanceConfig.DBL_SHOTGUN_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Plasma Rifle",   WeaponRole.BURST,
                BalanceConfig.PLASMA_RIFLE_CLIP_SIZE, BalanceConfig.PLASMA_RIFLE_DAMAGE, BalanceConfig.PLASMA_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Assault Rifle",  WeaponRole.WORKHORSE,
                BalanceConfig.ASSAULT_RIFLE_CLIP_SIZE, BalanceConfig.ASSAULT_RIFLE_DAMAGE, BalanceConfig.ASSAULT_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Chaingun",       WeaponRole.WORKHORSE,
                BalanceConfig.CHAINGUN_CLIP_SIZE, BalanceConfig.CHAINGUN_DAMAGE, BalanceConfig.CHAINGUN_RELOAD_TIME_TICKS, 1);
        // Railgun scored at FULL charge (its intended engagement state).
        printWeaponRow("Railgun(full)",  WeaponRole.HEAVY,
                BalanceConfig.RAILGUN_CLIP_SIZE,
                BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE[BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE.length - 1],
                BalanceConfig.RAILGUN_RELOAD_TIME_TICKS, 1);
        // Grenade scored on its centre splash damage.
        printWeaponRow("Grenade Lchr",   WeaponRole.HEAVY,
                BalanceConfig.GRENADE_CLIP_SIZE, BalanceConfig.GRENADE_SPLASH_DAMAGE, BalanceConfig.GRENADE_RELOAD_TIME_TICKS, 1);
    }

    private static void printWeaponRow(String weaponName, WeaponRole weaponRole,
                                       int clipSize, int damagePerShot, int reloadTicks, int ammoPerShot) {
        float sustainedDamagePerTurn = GameMath.sustainedDamagePerTurn(clipSize, damagePerShot, reloadTicks);
        float ammoEfficiency = GameMath.ammoEfficiency(damagePerShot, ammoPerShot);
        float ammoEfficiencyNormalized = ammoEfficiency / BalanceConfig.REFERENCE_AMMO_EFFICIENCY;
        float powerScore = GameMath.weaponPowerScore(sustainedDamagePerTurn, ammoEfficiencyNormalized);

        boolean insideBand = powerScore >= weaponRole.bandMinimum && powerScore <= weaponRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", weaponRole.bandMinimum, weaponRole.bandMaximum);

        System.out.printf("%-16s %-10s %8.1f %8.1f %10.1f %12s %-6s%n",
                weaponName, weaponRole.name(), sustainedDamagePerTurn, ammoEfficiency,
                powerScore, bandText, bandVerdict(insideBand, powerScore, weaponRole.bandMinimum));
    }

    // -----------------------------------------------------------------------------------
    // ENEMIES — threat points vs role band, plus the golden-ratio (TTD/TTK) sanity check.
    // Golden ratio uses the player's SUSTAINED reference DPT (REFERENCE_PLAYER_DPT, contract
    // decision idea-A iteration 2 — option b) for TTK and reference eHP for TTD.
    // -----------------------------------------------------------------------------------
    private static void printEnemyTable() {
        System.out.println("ENEMIES");
        System.out.printf("%-16s %-11s %5s %6s %5s %8s %10s %-6s %9s %-6s%n",
                "enemy", "role", "eHP", "atkDmg", "cad", "posMult", "TP", "in?", "TTD/TTK", "gr?");
        System.out.println("------------------------------------------------------------------------------------");

        // cadence: ranged enemies attack every turn (1); melee enemies attack on their move cadence.
        printEnemyRow("Gore Biter",  EnemyRole.CHAFF,   BalanceConfig.GORE_BITER_MAX_HEALTH,
                BalanceConfig.GORE_BITER_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Eye Tyrant",  EnemyRole.CHAFF,   BalanceConfig.EYE_TYRANT_MAX_HEALTH,
                BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Acid Drone",  EnemyRole.SOLDIER, BalanceConfig.ACID_DRONE_MAX_HEALTH,
                BalanceConfig.ACID_DRONE_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Void Shroud", EnemyRole.SOLDIER, BalanceConfig.VOID_SHROUD_MAX_HEALTH,
                BalanceConfig.VOID_SHROUD_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Mire Wraith", EnemyRole.SOLDIER, BalanceConfig.MIRE_WRAITH_MAX_HEALTH,
                BalanceConfig.MIRE_WRAITH_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Shell Brute", EnemyRole.BRUISER, BalanceConfig.SHELL_BRUTE_MAX_HEALTH,
                BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_MELEE,      true);
        printEnemyRow("Plague Hulk", EnemyRole.SOLDIER, BalanceConfig.PLAGUE_HULK_MAX_HEALTH,
                BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE, BalanceConfig.PLAGUE_HULK_MOVE_EVERY_N_TURNS,
                BalanceConfig.POSITIONAL_MULT_MELEE,      false);
        // Iron Stalker scored on its melee profile (its higher damage line), like the contract worked example.
        printEnemyRow("Iron Stalker", EnemyRole.MINI_ELITE, BalanceConfig.IRON_STALKER_MAX_HEALTH,
                BalanceConfig.IRON_STALKER_MELEE_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, true);
    }

    private static void printEnemyRow(String enemyName, EnemyRole enemyRole, int rawHealth,
                                      int attackDamage, int attackCadenceTurns,
                                      float positionalMultiplier, boolean useBruiserGoldenBand) {
        // Enemies currently have no dodge or flat reduction, so eHP == raw HP.
        float enemyEffectiveHitPoints = GameMath.effectiveHitPoints(rawHealth, 0f, 0f, 0f, 0f);
        float threatPoints = GameMath.threatPoints(attackDamage, attackCadenceTurns,
                enemyEffectiveHitPoints, BalanceConfig.REFERENCE_PLAYER_DPT, positionalMultiplier);
        boolean insideBand = threatPoints >= enemyRole.bandMinimum && threatPoints <= enemyRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", enemyRole.bandMinimum, enemyRole.bandMaximum);

        // Golden ratio (CONTRACT DECISION idea-A, iteration 2): TTK by the player's SUSTAINED
        // reference DPT (option b), NOT best burst. Best burst pinned TTK at 1 for anything the
        // shotgun one-shot; sustained DPT is the player's realistic kill rate and the same yardstick
        // the TP normaliser uses. TTD by enemy DPT into reference eHP (unchanged).
        int turnsToKill = GameMath.turnsToKill(enemyEffectiveHitPoints, BalanceConfig.REFERENCE_PLAYER_DPT);
        float enemyDamagePerTurn = (float) attackDamage / Math.max(1, attackCadenceTurns);
        int turnsToDie = GameMath.turnsToKill(BalanceConfig.REFERENCE_PLAYER_EHP, enemyDamagePerTurn);
        float goldenRatio = GameMath.goldenRatio(turnsToDie, turnsToKill);

        float goldenMinimum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MIN : BalanceConfig.GOLDEN_RATIO_TRASH_MIN;
        float goldenMaximum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MAX : BalanceConfig.GOLDEN_RATIO_TRASH_MAX;
        boolean goldenInside = goldenRatio >= goldenMinimum && goldenRatio <= goldenMaximum;

        System.out.printf("%-16s %-11s %5.0f %6d %5d %8.2f %10.1f %-6s %9.1f %-6s%n",
                enemyName, enemyRole.name(), enemyEffectiveHitPoints, attackDamage, attackCadenceTurns,
                positionalMultiplier, threatPoints, bandVerdict(insideBand, threatPoints, enemyRole.bandMinimum),
                goldenRatio, bandVerdict(goldenInside, goldenRatio, goldenMinimum));
    }

    // -----------------------------------------------------------------------------------
    // BLOCK & DEFEND (strategy-combat-order-3) — Block is transient eHP. Priced as "turns of
    // survival bought" = baseBlock / REFERENCE_PLAYER_DPT. A single DEFEND should buy ~1 turn
    // (survTurns ≈ 1), so a defend does NOT inflate a role's TTK out of its golden-ratio band:
    // Block decays after BLOCK_DECAY_TURNS and is capped at BLOCK_MAX, so it can never compound
    // into immortality, and status DoT bypasses it entirely (the build answer to turtles).
    // -----------------------------------------------------------------------------------
    private static void printBlockTable() {
        System.out.println("BLOCK & DEFEND (order-3)");
        System.out.printf("%-12s %8s %8s %7s %10s %-6s%n",
                "role", "baseBlk", "blkMax", "decay", "survTurns", "in?");
        System.out.println("------------------------------------------------------------------");
        printBlockRow("SOLDIER",    BalanceConfig.DEFEND_BLOCK_GAIN_SOLDIER);
        printBlockRow("BRUISER",    BalanceConfig.DEFEND_BLOCK_GAIN_BRUISER);
        printBlockRow("MINI_ELITE", BalanceConfig.DEFEND_BLOCK_GAIN_MINI_ELITE);
        System.out.println("survTurns = baseBlk / REFERENCE_PLAYER_DPT (turns of survival one DEFEND buys).");
        System.out.println("in? = OK when survTurns is in [0.6, 2.0] — ~1 turn bought, never a stall.");
        System.out.printf("BRUISER also braces on a fixed cadence every %d turns; CHAFF/BOSS never brace.%n",
                BalanceConfig.DEFEND_BRUISER_CADENCE_TURNS);
        System.out.printf("Turtle trigger: HP <= %.0f%% and the player is positioned to hit next turn.%n",
                BalanceConfig.DEFEND_HP_THRESHOLD_FRACTION * 100f);
    }

    private static void printBlockRow(String roleName, int baseBlock) {
        float survivalTurns = baseBlock / BalanceConfig.REFERENCE_PLAYER_DPT;
        boolean inBand = survivalTurns >= 0.6f && survivalTurns <= 2.0f;
        System.out.printf("%-12s %8d %8d %7d %10.2f %-6s%n",
                roleName, baseBlock, BalanceConfig.BLOCK_MAX, BalanceConfig.BLOCK_DECAY_TURNS,
                survivalTurns, inBand ? "OK" : "OUT!");
    }

    // -----------------------------------------------------------------------------------
    // SPECIAL MOVE-SETS (order-5) — each scripted archetype's ability cadence and catalogue.
    // A move-set changes an enemy's EFFECTIVE threat: buff/debuff/area moves raise its blended DPT and
    // summons add spawned TP. The hard summon caps bound that headroom so the encounter budget holds.
    // This table lists which archetypes are scripted; the TP bands above still gate their base stats.
    // -----------------------------------------------------------------------------------
    private static void printMoveSetTable() {
        System.out.println("SPECIAL MOVE-SETS (order-5)");
        System.out.println("------------------------------------------------------------------------------------");
        System.out.printf("%-16s %-11s %-9s %s%n", "archetype", "role", "cadence", "abilities");
        System.out.println("------------------------------------------------------------------------------------");
        for (ge.tbegvadze.toon3d.enemy.EnemyType type : ge.tbegvadze.toon3d.enemy.EnemyType.values()) {
            ge.tbegvadze.toon3d.enemy.SpecialAbility[] moveSet = type.moveSet();
            if (moveSet.length == 0) continue; // trivial chaff/boss — no scripted specials
            StringBuilder abilities = new StringBuilder();
            for (int index = 0; index < moveSet.length; index++) {
                if (index > 0) abilities.append(", ");
                abilities.append(moveSet[index].name());
            }
            System.out.printf("%-16s %-11s %-9d %s%n",
                    type.displayName(), type.role().name(),
                    type.specialAbilityCadenceTurns(), abilities);
        }
        System.out.println("------------------------------------------------------------------------------------");
        System.out.println("cadence = enemy turns between specials; every damaging special is telegraphed 1 turn ahead.");
    }

    // -----------------------------------------------------------------------------------
    // UPGRADE CARDS (idea 5) — every level-up card priced in power points (PP) vs the budget.
    // PP = %-gain to reference DPT (offence) or reference eHP (survivability), computed straight
    // from the card's stat deltas through GameMath. Each card MUST land in the budget band, so the
    // total PP at level L is build-independent (= L * budget). Trade-off cards net to ~budget.
    // -----------------------------------------------------------------------------------
    private static void printUpgradeCardTable() {
        float budget    = GameBalance.LEVEL_UP_BUDGET_PP;
        float tolerance = GameBalance.LEVEL_UP_BUDGET_TOLERANCE;
        float bandMinimum = budget * (1f - tolerance);
        float bandMaximum = budget * (1f + tolerance);

        System.out.println("UPGRADE CARDS (idea 5) — budget = " + String.format("%.0f", budget)
                + " PP   band = " + String.format("%.1f-%.1f", bandMinimum, bandMaximum)
                + " PP   (offered " + GameBalance.LEVEL_UP_CARDS_OFFERED + "/level)");
        System.out.printf("%-20s %-9s %-13s %8s %-8s %-6s%n",
                "card", "pool", "lever", "PP", "tradeoff", "in?");
        System.out.println("------------------------------------------------------------------------------------");

        boolean allInBand = true;
        for (ge.tbegvadze.toon3d.progression.UpgradeCard card
                : ge.tbegvadze.toon3d.progression.UpgradeCard.values()) {
            float powerPoints = card.estimatedPowerPoints();
            boolean inBand = powerPoints >= bandMinimum && powerPoints <= bandMaximum;
            allInBand &= inBand;
            System.out.printf("%-20s %-9s %-13s %8.1f %-8s %-6s%n",
                    card.displayName, card.pool.name(), card.lever.name(), powerPoints,
                    card.isTradeOff() ? "YES" : "no",
                    bandVerdict(inBand, powerPoints, bandMinimum));
        }
        System.out.println("------------------------------------------------------------------------------------");
        System.out.println("INVARIANT: every card in band => total PP at level L = L * budget (build-independent).  "
                + (allInBand ? "ALL CARDS IN BAND" : "*** OUT-OF-BAND CARD(S) — RE-PRICE ***"));
    }

    private static String bandVerdict(boolean insideBand, float value, float bandMinimum) {
        if (insideBand) {
            return "OK";
        }
        return value < bandMinimum ? "UNDER" : "OVER";
    }

    // -----------------------------------------------------------------------------------
    // ENCOUNTER BUDGET — the floor TP budget and the planned roster's composition (idea 4).
    // Plans a roster per depth via EncounterBudgetPlanner and checks idea 4's rules:
    //   anchor present, no single TYPE over the per-type cap, both ranged AND melee present.
    // Uses a fixed seed so the report is reproducible run-to-run.
    // -----------------------------------------------------------------------------------
    private static void printEncounterTable() {
        System.out.println("ENCOUNTER BUDGET (idea 4) — base budget = "
                + String.format("%.0f", BalanceConfig.FLOOR_BASE_THREAT_POINT_BUDGET) + " TP at depth 1");
        System.out.printf("%-6s %8s %8s %6s %-14s %-9s %-7s %-7s%n",
                "depth", "budget", "spent", "count", "anchor", "maxType%", "mix?", "rules?");
        System.out.println("------------------------------------------------------------------------------------");
        int[] depths = {1, 2, 3, 5, 8};
        for (int depth : depths) {
            printEncounterRow(depth);
        }
    }

    private static void printEncounterRow(int depth) {
        // Deterministic seed per depth so the audit is stable.
        ge.tbegvadze.toon3d.level.EncounterBudgetPlanner planner =
                new ge.tbegvadze.toon3d.level.EncounterBudgetPlanner(depth, new java.util.Random(1234L + depth));
        ge.tbegvadze.toon3d.level.EncounterBudgetPlanner.Plan plan = planner.plan();

        java.util.List<ge.tbegvadze.toon3d.enemy.EnemyType> roster = plan.enemies();

        // Largest single-type TP fraction of budget.
        java.util.EnumMap<ge.tbegvadze.toon3d.enemy.EnemyType, Float> byType =
                new java.util.EnumMap<>(ge.tbegvadze.toon3d.enemy.EnemyType.class);
        boolean hasRanged = false;
        boolean hasMelee  = false;
        for (ge.tbegvadze.toon3d.enemy.EnemyType type : roster) {
            byType.merge(type, plan.threatOf(type), Float::sum);
            if (type.isRanged()) hasRanged = true; else hasMelee = true;
        }
        float maxTypeFraction        = 0f;   // informational: largest single-type share
        float maxFillTypeFraction    = 0f;    // cap check: largest NON-anchor type share
        for (java.util.Map.Entry<ge.tbegvadze.toon3d.enemy.EnemyType, Float> entry : byType.entrySet()) {
            float fraction = entry.getValue() / plan.floorBudget();
            maxTypeFraction = Math.max(maxTypeFraction, fraction);
            if (entry.getKey() != plan.anchor()) {
                maxFillTypeFraction = Math.max(maxFillTypeFraction, fraction);
            }
        }

        boolean anchorOk = plan.anchor() != null;
        // Anchor is exempt from the per-type cap; fill types must respect it.
        boolean typeOk   = maxFillTypeFraction <= BalanceConfig.ENCOUNTER_MAX_SINGLE_TYPE_FRACTION + 0.001f;
        boolean mixOk    = hasRanged && hasMelee;
        boolean allRules = anchorOk && typeOk && mixOk;

        String anchorName = plan.anchor() == null ? "(none)" : plan.anchor().displayName();
        System.out.printf("%-6d %8.0f %8.0f %6d %-14s %-9.0f %-7s %-7s%n",
                depth, plan.floorBudget(), plan.spentThreatPoints(), roster.size(),
                anchorName, maxTypeFraction * 100f,
                mixOk ? "OK" : "NO", allRules ? "OK" : "CHECK");
    }

    // -----------------------------------------------------------------------------------
    // DEPTH COUPLING — the fairness-over-depth invariant (balance contract, DEPTH SCALING).
    // The player's power curve (LINEAR: level-up power points accumulate per floor,
    // GameMath.playerPowerAtDepth) must stay coupled to the enemy threat curve (COMPOUND:
    // GameMath.depthThreatScale). Their ratio must hold in [DEPTH_COUPLING_RATIO_MIN, MAX]:
    // below = unfair-hard (player fell behind), above = trivial-easy (player outscaled it).
    // This table is what the SECTION 3 enemy depth-scale tune is verified against.
    // -----------------------------------------------------------------------------------
    private static void printDepthCouplingTable() {
        System.out.println("DEPTH COUPLING — player power vs enemy threat (band "
                + String.format("%.2f-%.2f", BalanceConfig.DEPTH_COUPLING_RATIO_MIN,
                        BalanceConfig.DEPTH_COUPLING_RATIO_MAX) + ")");
        System.out.println("  enemy scale = " + BalanceConfig.ENEMY_HEALTH_SCALE_PER_DEPTH + " HP * "
                + BalanceConfig.ENEMY_DAMAGE_SCALE_PER_DEPTH + " dmg / floor (compound) ; player = "
                + String.format("%.0f", GameBalance.LEVEL_UP_BUDGET_PP) + " PP * "
                + BalanceConfig.EXPECTED_LEVELS_PER_DEPTH + " level/floor (linear)");
        System.out.printf("%-6s %10s %10s %8s %-12s%n", "depth", "player", "enemy", "ratio", "in band?");
        System.out.println("------------------------------------------------------------------------------------");
        int[] depths = {1, 2, 3, 4, 5, 8, 10, 12, 15};
        for (int depth : depths) {
            float playerPower = GameMath.playerPowerAtDepth(GameBalance.LEVEL_UP_BUDGET_PP,
                    BalanceConfig.EXPECTED_LEVELS_PER_DEPTH, depth);
            float enemyThreat = GameMath.depthThreatScale(BalanceConfig.ENEMY_HEALTH_SCALE_PER_DEPTH,
                    BalanceConfig.ENEMY_DAMAGE_SCALE_PER_DEPTH, depth);
            float ratio = GameMath.depthCouplingRatio(playerPower, enemyThreat);
            boolean inBand = ratio >= BalanceConfig.DEPTH_COUPLING_RATIO_MIN
                    && ratio <= BalanceConfig.DEPTH_COUPLING_RATIO_MAX;
            String verdict = inBand ? "OK"
                    : (ratio < BalanceConfig.DEPTH_COUPLING_RATIO_MIN ? "UNDER(hard)" : "OVER(easy)");
            System.out.printf("%-6d %10.3f %10.3f %8.3f %-12s%n", depth, playerPower, enemyThreat, ratio, verdict);
        }
    }

    // -----------------------------------------------------------------------------------
    // SCARCITY — the model floor's SUPPLY vs DEMAND, scarcity ratio S, per-weapon S,
    // reserve banking ceiling, and the heal economy's net HP drain (idea 3).
    // Every number is computed from BalanceConfig through GameMath, so it cannot drift.
    // -----------------------------------------------------------------------------------
    private static void printScarcityTable() {
        // DEMAND = sum of every model-floor enemy's eHP (eHP == raw HP: no dodge/reduction).
        float demand =
                  BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT  * enemyEffectiveHitPoints(BalanceConfig.GORE_BITER_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT  * enemyEffectiveHitPoints(BalanceConfig.EYE_TYRANT_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT * enemyEffectiveHitPoints(BalanceConfig.SHELL_BRUTE_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT * enemyEffectiveHitPoints(BalanceConfig.PLAGUE_HULK_MAX_HEALTH);
        int enemyCount = BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT;

        // Expected ammo boxes per floor, split uniformly across the 5 floor-droppable types
        // (matches the generator's randomAmmoChar() uniform roll).
        float expectedBoxes = GameMath.expectedAmmoBoxesPerFloor(
                BalanceConfig.MODEL_FLOOR_ROOM_COUNT, BalanceConfig.LEVEL_GEN_AMMO_CHANCE_PER_ROOM,
                enemyCount, BalanceConfig.ENEMY_AMMO_DROP_CHANCE);
        float boxesPerType = expectedBoxes / BalanceConfig.MODEL_FLOOR_AMMO_TYPE_COUNT;

        System.out.println("SCARCITY — model floor (depth 1): " + enemyCount + " enemies, "
                + BalanceConfig.MODEL_FLOOR_ROOM_COUNT + " rooms, DEMAND=" + String.format("%.0f", demand)
                + " dmg ; expected ammo boxes/floor=" + String.format("%.2f", expectedBoxes)
                + " (" + String.format("%.2f", boxesPerType) + "/type)");
        System.out.printf("%-10s %7s %9s %8s %10s %-7s %12s%n",
                "ammoType", "boxSize", "dmg/unit", "supply", "perWpnS", "<0.6?", "bankFloors");
        System.out.println("------------------------------------------------------------------------------------");

        // Representative damage-per-unit = the per-shot damage of the weapon that eats this
        // ammo (one shot costs one unit), so supply = boxes * boxSize * damagePerShot.
        float railgunFull = BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE[BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE.length - 1];
        float bulletsSupply = printScarcityRow("Bullets", boxesPerType, BalanceConfig.AMMO_BOX_BULLETS,
                BalanceConfig.ASSAULT_RIFLE_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_BULLETS, demand);
        float shellsSupply  = printScarcityRow("Shells",  boxesPerType, BalanceConfig.AMMO_BOX_SHELLS,
                BalanceConfig.SHOTGUN_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_SHELLS, demand);
        float cellsSupply   = printScarcityRow("Cells",   boxesPerType, BalanceConfig.AMMO_BOX_CELLS,
                BalanceConfig.PLASMA_RIFLE_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_CELLS, demand);
        float rocketsSupply = printScarcityRow("Rockets", boxesPerType, BalanceConfig.AMMO_BOX_ROCKETS,
                BalanceConfig.GRENADE_SPLASH_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_ROCKETS, demand);
        float slugsSupply   = printScarcityRow("Slugs",   boxesPerType, BalanceConfig.RAILGUN_PICKUP_SLUGS,
                railgunFull, BalanceConfig.RAILGUN_MAX_SLUGS, demand);

        float totalSupply = bulletsSupply + shellsSupply + cellsSupply + rocketsSupply + slugsSupply;
        float scarcityRatio = GameMath.scarcityRatio(totalSupply, demand);
        boolean ratioInBand = scarcityRatio >= BalanceConfig.SCARCITY_RATIO_FLOOR_MIN
                && scarcityRatio <= BalanceConfig.SCARCITY_RATIO_FLOOR_MAX;
        System.out.println("------------------------------------------------------------------------------------");
        System.out.printf("FLOOR-WIDE  SUPPLY=%.0f  DEMAND=%.0f  S=%.2f  band=%.2f-%.2f  %s%n",
                totalSupply, demand, scarcityRatio,
                BalanceConfig.SCARCITY_RATIO_FLOOR_MIN, BalanceConfig.SCARCITY_RATIO_FLOOR_MAX,
                bandVerdict(ratioInBand, scarcityRatio, BalanceConfig.SCARCITY_RATIO_FLOOR_MIN));

        printHealEconomy(demand, enemyCount);
    }

    /** Prints one ammo-type row and returns that type's supply damage. */
    private static float printScarcityRow(String ammoType, float boxesPerType, int boxSize,
                                          float damagePerUnit, int reserveCap, float demand) {
        float supply = GameMath.ammoSupplyDamage(boxesPerType, boxSize, damagePerUnit);
        float perWeaponShare = GameMath.scarcityRatio(supply, demand);
        boolean underCap = perWeaponShare < BalanceConfig.SCARCITY_PER_WEAPON_MAX;
        float bankFloors = GameMath.reserveBankingFloors(reserveCap, damagePerUnit, demand);
        System.out.printf("%-10s %7d %9.0f %8.0f %10.2f %-7s %12.2f%n",
                ammoType, boxSize, damagePerUnit, supply, perWeaponShare,
                underCap ? "OK" : "OVER", bankFloors);
        return supply;
    }

    /** Prints the heal economy: incoming damage, heal supply, and net HP drain vs band. */
    private static void printHealEconomy(float demand, int enemyCount) {
        // Total enemy damage-per-turn across the model floor (melee cadence folded in).
        float totalEnemyDamagePerTurn =
                  BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT  * (BalanceConfig.GORE_BITER_ATTACK_DAMAGE  / 1f)
                + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT  * (BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE  / 1f)
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT * (BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE / 1f)
                + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT
                        * (BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE / (float) BalanceConfig.PLAGUE_HULK_MOVE_EVERY_N_TURNS);

        float incoming = GameMath.incomingDamagePerFloor(totalEnemyDamagePerTurn,
                BalanceConfig.MODEL_FLOOR_TURNS_ENGAGED_PER_ENEMY, BalanceConfig.MODEL_FLOOR_AVOIDANCE_FACTOR);

        float averageMedkitHeal = (BalanceConfig.MEDKIT_STIM_HEAL + BalanceConfig.MEDKIT_FULL_HEAL) / 2f;
        float averageArmourValue = (BalanceConfig.ARMOUR_SHARD_VALUE + BalanceConfig.ARMOUR_VEST_VALUE) / 2f;
        float healSupply = GameMath.healSupplyPerFloor(BalanceConfig.MODEL_FLOOR_EXPECTED_MEDKITS, averageMedkitHeal,
                BalanceConfig.MODEL_FLOOR_EXPECTED_ARMOUR_PICKUPS, averageArmourValue);

        float netDrain = GameMath.netHpDrainPerFloor(incoming, healSupply);
        float drainFraction = netDrain / BalanceConfig.REFERENCE_PLAYER_EHP;
        boolean drainInBand = drainFraction >= BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN
                && drainFraction <= BalanceConfig.HEAL_NET_DRAIN_FRACTION_MAX;

        // Informational: what a full medkit buys, in survival turns, at the floor's average rate.
        int floorEngagementTurns = Math.max(1, enemyCount * BalanceConfig.MODEL_FLOOR_TURNS_ENGAGED_PER_ENEMY);
        float averageIncomingDamagePerTurn = incoming / floorEngagementTurns;
        float fullMedkitTurns = GameMath.survivalTurnsBought(BalanceConfig.MEDKIT_FULL_HEAL, averageIncomingDamagePerTurn);

        System.out.println();
        System.out.println("HEAL ECONOMY — model floor");
        System.out.printf("  INCOMING=%.0f  HEAL_SUPPLY=%.0f  netHpDrain=%.0f  (%.1f%% of %.0f eHP ; band %.0f-%.0f%%)  %s%n",
                incoming, healSupply, netDrain, drainFraction * 100f, BalanceConfig.REFERENCE_PLAYER_EHP,
                BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN * 100f, BalanceConfig.HEAL_NET_DRAIN_FRACTION_MAX * 100f,
                bandVerdict(drainInBand, drainFraction, BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN));
        System.out.printf("  full medkit (%d HP) buys %.1f survival-turns at %.1f avg incoming dmg/turn (informational)%n",
                BalanceConfig.MEDKIT_FULL_HEAL, fullMedkitTurns, averageIncomingDamagePerTurn);
    }

    /** Enemy eHP with no dodge or flat reduction (the contract rule for current enemies). */
    private static float enemyEffectiveHitPoints(int rawHealth) {
        return GameMath.effectiveHitPoints(rawHealth, 0f, 0f, 0f, 0f);
    }

    // -----------------------------------------------------------------------------------
    // HAZARDS (idea 4, Pillar 3) — fold terrain danger into the Threat-Point contract.
    // A hazard tile has no HP, so its TP = damagePerTurn * careless-turns-stood * positional
    // (GameMath.hazardTileThreatPoints). N such tiles raise a room's effective floor TP by ~N×
    // this — that is how "a room full of fire raises its effective TP" (idea 4) is quantified.
    // -----------------------------------------------------------------------------------
    private static void printHazardTable() {
        System.out.println("HAZARDS (idea 4, Pillar 3) — turnsStood=" + BalanceConfig.HAZARD_THREAT_TURNS_STOOD
                + " (careless-player reference)");
        System.out.printf("%-8s %10s %8s %10s %12s%n",
                "hazard", "dmg/turn", "TP/tile", "lifetime", "TP per 6 tiles");
        System.out.println("------------------------------------------------------------------------------------");

        // Fire applies BURNING at a flat per-turn magnitude; toxic STACKS, so a careless stand of
        // turnsStood turns averages ~turnsStood/2 stacks — model its damage/turn at that average.
        float fireDamagePerTurn  = EffectConstants.BURN_DAMAGE_PER_TURN;
        float toxicAverageStacks = Math.max(1f, BalanceConfig.HAZARD_THREAT_TURNS_STOOD / 2f);
        float toxicDamagePerTurn = EffectConstants.POISON_DAMAGE_PER_STACK * toxicAverageStacks;

        printHazardRow("Fire 'i'",  fireDamagePerTurn,  BalanceConfig.HAZARD_FIRE_LIFETIME_TURNS);
        printHazardRow("Toxic 'q'", toxicDamagePerTurn, BalanceConfig.HAZARD_TOXIC_LIFETIME_TURNS);
        System.out.println("  Hazards damage BOTH sides (player AND enemies) via BURNING/POISONED — two-sided by design.");
    }

    private static void printHazardRow(String hazardName, float damagePerTurn, int lifetimeTurns) {
        float threatPerTile = GameMath.hazardTileThreatPoints(damagePerTurn,
                BalanceConfig.HAZARD_THREAT_TURNS_STOOD, BalanceConfig.POSITIONAL_MULT_MELEE);
        System.out.printf("%-8s %10.1f %8.1f %10d %12.1f%n",
                hazardName, damagePerTurn, threatPerTile, lifetimeTurns, threatPerTile * 6f);
    }

    // -----------------------------------------------------------------------------------
    // TELEGRAPH AUDIT (idea 4, Pillar 5) — the fairness contract.
    // RULE: every attack that can deal > TELEGRAPH_MAX_UNTELEGRAPHED_HIT_FRACTION of reference eHP
    // in ONE hit MUST be telegraphed or avoidable. An UN-telegraphed attack whose depth-1 hit
    // already exceeds the cap FAILS. "cap@" is the depth at which the attack first crosses the cap
    // (informational): telegraphed/avoidable attacks are allowed to cross it.
    // -----------------------------------------------------------------------------------
    private static void printTelegraphAudit() {
        float cap = BalanceConfig.REFERENCE_PLAYER_EHP * BalanceConfig.TELEGRAPH_MAX_UNTELEGRAPHED_HIT_FRACTION;
        System.out.printf("TELEGRAPH AUDIT (idea 4, Pillar 5) — cap = %.0f%% of %.0f eHP = %.0f dmg / un-telegraphed hit%n",
                BalanceConfig.TELEGRAPH_MAX_UNTELEGRAPHED_HIT_FRACTION * 100f,
                BalanceConfig.REFERENCE_PLAYER_EHP, cap);
        System.out.printf("%-22s %9s %-13s %6s %-7s%n",
                "attack", "hit@d1", "readable?", "cap@", "verdict");
        System.out.println("------------------------------------------------------------------------------------");

        // Readable kinds: TELE = wind-up telegraph, LANE = ranged cardinal-line tell (you can see
        // when you're in its lane), FACE = positional counter (rotate to deny it), NONE = burst.
        printTelegraphRow("Gore Biter bite",   BalanceConfig.GORE_BITER_ATTACK_DAMAGE,  "NONE", cap);
        printTelegraphRow("Plague Hulk smash",  BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE, "NONE", cap);
        printTelegraphRow("Void Shroud strike", BalanceConfig.VOID_SHROUD_ATTACK_DAMAGE, "NONE", cap);
        printTelegraphRow("Void Shroud flank",
                Math.round(BalanceConfig.VOID_SHROUD_ATTACK_DAMAGE * BalanceConfig.VOID_SHROUD_FLANK_DAMAGE_MULTIPLIER),
                "FACE", cap);
        printTelegraphRow("Shell Brute melee",  BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE, "NONE", cap);
        printTelegraphRow("Shell Brute CHARGE",
                Math.round(BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE * BalanceConfig.SHELL_BRUTE_CHARGE_DAMAGE_MULTIPLIER),
                "TELE", cap);
        printTelegraphRow("Iron Stalker melee", BalanceConfig.IRON_STALKER_MELEE_DAMAGE, "NONE", cap);
        printTelegraphRow("Eye Tyrant beam",    BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE,  "LANE", cap);
        printTelegraphRow("Acid Drone spit",    BalanceConfig.ACID_DRONE_ATTACK_DAMAGE,  "LANE", cap);
        printTelegraphRow("Mire Wraith acid",   BalanceConfig.MIRE_WRAITH_ATTACK_DAMAGE, "LANE", cap);
        printTelegraphRow("Iron Stalker shot",  BalanceConfig.IRON_STALKER_RANGED_DAMAGE, "LANE", cap);
        // Bosses telegraph through their BossAttackPattern phases.
        printTelegraphRow("Overseer charge",    EnemyConstants.OVERSEER_CHARGE_DAMAGE,    "TELE", cap);
        printTelegraphRow("Hell Baron cleave2", EnemyConstants.HELL_BARON_CLEAVE_DAMAGE_P2, "TELE", cap);
    }

    private static void printTelegraphRow(String attackName, int baseHit, String readable, float cap) {
        boolean avoidable = !"NONE".equals(readable);
        // Depth at which this hit first crosses the cap, scanning a generous depth range.
        int crossingDepth = -1;
        for (int depth = 1; depth <= 30; depth++) {
            float hit = baseHit * GameBalance.enemyDamageScaleForDepth(depth);
            if (hit > cap) { crossingDepth = depth; break; }
        }
        String crossText = (crossingDepth == -1) ? ">30" : Integer.toString(crossingDepth);
        // FAIL only when an UN-telegraphed attack already exceeds the cap at depth 1.
        boolean failsContract = !avoidable && baseHit > cap;
        String verdict = failsContract ? "FAIL" : "OK";
        System.out.printf("%-22s %9d %-13s %6s %-7s%n", attackName, baseHit, readable, crossText, verdict);
    }

    // -----------------------------------------------------------------------------------
    // BOSS RULESET (idea 6) — bosses are tuned by FORMULA, not by flat HP.
    // Bosses break the trash-mob TP/golden-ratio bands, so they get their own contract:
    // HP is DERIVED from a fight-length target against the EXPECTED player DPT at depth
    // (RULE 1), the fight is capped from above (RULE 2), boss DPT is a survival check
    // (RULE 3), and no single hit may break the fairness caps (RULE 3). Boss FIGHTS are
    // deferred, so this section re-derives what the CURRENT placeholder bosses SHOULD be
    // and flags how far the placeholders sit from the formula — exactly the "re-derive me"
    // signal the boss work will act on. Every number is BalanceConfig through GameMath.
    // -----------------------------------------------------------------------------------
    private static void printBossRulesetTable() {
        float targetMin = BalanceConfig.BOSS_TARGET_FIGHT_TURNS_ACT_MIN;
        float targetMax = BalanceConfig.BOSS_TARGET_FIGHT_TURNS_ACT_MAX;
        float targetMid = (targetMin + targetMax) / 2f;
        float refEhp = BalanceConfig.REFERENCE_PLAYER_EHP;

        System.out.println("BOSS RULESET (idea 6) — act-boss target fight = "
                + String.format("%.0f-%.0f", targetMin, targetMax) + " turns ; survivalRatio band "
                + String.format("%.2f-%.2f", BalanceConfig.BOSS_SURVIVAL_CHECK_RATIO_MIN,
                        BalanceConfig.BOSS_SURVIVAL_CHECK_RATIO_MAX)
                + " ; single-hit caps: telegraph >"
                + String.format("%.0f%%", BalanceConfig.TELEGRAPH_MAX_UNTELEGRAPHED_HIT_FRACTION * 100f)
                + " eHP, hard "
                + String.format("%.0f%%", BalanceConfig.BOSS_HARD_SINGLE_HIT_FRACTION * 100f) + " eHP");
        System.out.printf("%-12s %5s %7s %14s %9s %-7s %9s %10s %-10s%n",
                "boss", "depth", "expDPT", "derivedHP", "litHP", "HP?", "fairDPT", "bigHit%eHP", "hitVerdict");
        System.out.println("------------------------------------------------------------------------------------");

        // Current placeholder bosses: their depth, placeholder HP, and biggest single hit.
        // Each divides ONE HP bar across its phases (it is not RE-fought), so multiPhaseFactor = 1.0
        // (matches the idea's Corruptor sanity check 450 ~= 25 * 18 * 1.0).
        printBossRow("Overseer", EnemyConstants.OVERSEER_DEPTH, EnemyConstants.OVERSEER_MAX_HP,
                EnemyConstants.OVERSEER_CHARGE_DAMAGE, true,
                targetMin, targetMax, targetMid, refEhp);
        printBossRow("Corruptor", EnemyConstants.CORRUPTOR_DEPTH, EnemyConstants.CORRUPTOR_MAX_HP,
                EnemyConstants.CORRUPTOR_ACID_DAMAGE, false,
                targetMin, targetMax, targetMid, refEhp);
        printBossRow("Hell Baron", EnemyConstants.HELL_BARON_DEPTH, EnemyConstants.HELL_BARON_MAX_HP,
                EnemyConstants.HELL_BARON_CLEAVE_DAMAGE_P2, true,
                targetMin, targetMax, targetMid, refEhp);

        System.out.println("------------------------------------------------------------------------------------");
        // Phase seams for a 3-phase act boss (RULE 4): where mechanics escalate.
        System.out.printf("  phase seams (3-phase act boss): %.0f%% -> %.0f%% -> %.0f%% (death)  [GameMath.bossPhaseHealthThreshold]%n",
                GameMath.bossPhaseHealthThreshold(1, 3) * 100f,
                GameMath.bossPhaseHealthThreshold(2, 3) * 100f,
                GameMath.bossPhaseHealthThreshold(3, 3) * 100f);
        System.out.println("  litHP are PLACEHOLDERS: HP? flags the literal vs the derived band. Re-derive when boss fights ship.");
    }

    private static void printBossRow(String bossName, int depth, int placeholderHp,
                                     int biggestSingleHit, boolean biggestHitTelegraphed,
                                     float targetMinTurns, float targetMaxTurns, float targetMidTurns,
                                     float referenceEffectiveHitPoints) {
        // Expected OFFENCE power points the average player has invested by this depth (idea 5 bridge):
        //   fraction-of-budget * budget-per-level * (levels-per-floor * depth).
        float expectedOffencePowerPoints = BalanceConfig.BOSS_EXPECTED_OFFENCE_BUDGET_FRACTION
                * GameBalance.LEVEL_UP_BUDGET_PP
                * (BalanceConfig.BOSS_EXPECTED_LEVELS_PER_DEPTH * depth);
        float expectedDamagePerTurn = GameMath.expectedPlayerSustainedDamagePerTurn(
                BalanceConfig.REFERENCE_PLAYER_DPT, expectedOffencePowerPoints);

        // Derived HP BAND from the fight-length target (RULE 1), one bar / no re-fight => factor 1.0.
        float derivedHpMin = GameMath.bossEffectiveHitPoints(expectedDamagePerTurn, targetMinTurns,
                BalanceConfig.BOSS_MULTI_PHASE_FACTOR_PER_PHASE);
        float derivedHpMax = GameMath.bossEffectiveHitPoints(expectedDamagePerTurn, targetMaxTurns,
                BalanceConfig.BOSS_MULTI_PHASE_FACTOR_PER_PHASE);
        boolean hpInBand = placeholderHp >= derivedHpMin && placeholderHp <= derivedHpMax;

        // Boss DPT the survival check wants at the mid target fight length (RULE 3).
        float fairDamagePerTurn = GameMath.bossDamagePerTurnForSurvivalCheck(
                referenceEffectiveHitPoints, targetMidTurns, BalanceConfig.BOSS_SURVIVAL_CHECK_RATIO_TARGET);

        // Biggest single hit vs the fairness caps (RULE 3).
        float hitFraction = GameMath.bossSingleHitFractionOfEffectiveHitPoints(
                biggestSingleHit, referenceEffectiveHitPoints);
        String hitVerdict;
        if (hitFraction > BalanceConfig.BOSS_HARD_SINGLE_HIT_FRACTION) {
            hitVerdict = "BANNED";                       // over the hard cap: never allowed.
        } else if (hitFraction > BalanceConfig.TELEGRAPH_MAX_UNTELEGRAPHED_HIT_FRACTION) {
            hitVerdict = biggestHitTelegraphed ? "TELE-OK" : "NEEDS-TELE";   // must be telegraphed.
        } else {
            hitVerdict = "OK";                           // under both caps.
        }

        System.out.printf("%-12s %5d %7.1f %14s %9d %-7s %9.1f %10.1f %-10s%n",
                bossName, depth, expectedDamagePerTurn,
                String.format("%.0f-%.0f", derivedHpMin, derivedHpMax), placeholderHp,
                hpInBand ? "OK" : (placeholderHp < derivedHpMin ? "UNDER" : "OVER"),
                fairDamagePerTurn, hitFraction * 100f, hitVerdict);
    }

    private static void printLegend() {
        System.out.println("LEGEND: in?/gr?/<0.6?/band = OK inside band, UNDER below, OVER above.");
        System.out.println("  sustDPT = (clip*dmg)/(clip+reload).  powerScore = sustDPT*sqrt(ammoEff/anchor).");
        System.out.println("  TP = (atkDmg/cadence) * (eHP/refDPT) * posMult.  TTD/TTK = golden ratio.");
        System.out.println("  S = SUPPLY/DEMAND (ranged ammo vs sum of enemy eHP).  perWpnS = that weapon's share.");
        System.out.println("  bankFloors = full reserve / floor demand (anti-hoard target ~"
                + BalanceConfig.RESERVE_BANKING_FLOORS_TARGET + ").  netHpDrain = INCOMING - HEAL_SUPPLY.");
        System.out.println("Out-of-band rows are tuning targets — see docs/balance-rule-system.txt.");
    }
}
