package ge.tbegvadze.toon3d.util;

/**
 * DEV-ONLY balance auditor. Prints the "living table" of every current weapon and enemy
 * with its computed Power Score / Threat Points, flags any content that falls OUTSIDE its
 * role band, and checks the golden ratio. This is the honest counterpart to the prose
 * contract in {@code docs/balance-rule-system.txt}: the numbers here come straight from
 * {@link BalanceConfig} through {@link GameMath}, so they cannot drift from the real game
 * values — when {@code BalanceConfig} changes, rerun this and regenerate the doc table.
 *
 * <p>This class is NOT part of the game loop. It touches no LibGDX render state and only
 * calls the pure contract formulas in {@link GameMath}, so it runs headless:
 * <pre>./gradlew core:run -PmainClass=ge.tbegvadze.toon3d.util.BalanceReport</pre>
 * (or run {@link #main(String[])} directly from an IDE). It exists purely to keep the
 * balance contract honest — the table can't lie.
 */
public final class BalanceReport {

    private BalanceReport() {}

    // Weapon roles and their power-score bands (from BalanceConfig).
    private enum WeaponRole {
        SIDEARM   (BalanceConfig.WEAPON_POWER_SIDEARM_MIN,   BalanceConfig.WEAPON_POWER_SIDEARM_MAX),
        WORKHORSE (BalanceConfig.WEAPON_POWER_WORKHORSE_MIN, BalanceConfig.WEAPON_POWER_WORKHORSE_MAX),
        BURST     (BalanceConfig.WEAPON_POWER_BURST_MIN,     BalanceConfig.WEAPON_POWER_BURST_MAX),
        HEAVY     (BalanceConfig.WEAPON_POWER_HEAVY_MIN,     BalanceConfig.WEAPON_POWER_HEAVY_MAX);

        final float bandMinimum;
        final float bandMaximum;

        WeaponRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    // Enemy roles and their threat-point bands (from BalanceConfig).
    private enum EnemyRole {
        CHAFF      (BalanceConfig.ENEMY_TP_CHAFF_MIN,      BalanceConfig.ENEMY_TP_CHAFF_MAX),
        SOLDIER    (BalanceConfig.ENEMY_TP_SOLDIER_MIN,    BalanceConfig.ENEMY_TP_SOLDIER_MAX),
        BRUISER    (BalanceConfig.ENEMY_TP_BRUISER_MIN,    BalanceConfig.ENEMY_TP_BRUISER_MAX),
        MINI_ELITE (BalanceConfig.ENEMY_TP_MINI_ELITE_MIN, BalanceConfig.ENEMY_TP_MINI_ELITE_MAX);

        final float bandMinimum;
        final float bandMaximum;

        EnemyRole(float bandMinimum, float bandMaximum) {
            this.bandMinimum = bandMinimum;
            this.bandMaximum = bandMaximum;
        }
    }

    public static void main(String[] commandLineArguments) {
        printHeader();
        printWeaponTable();
        System.out.println();
        printEnemyTable();
        System.out.println();
        printScarcityTable();
        System.out.println();
        printLegend();
    }

    private static void printHeader() {
        System.out.println("====================================================================================");
        System.out.println(" toon3D BALANCE RULE SYSTEM — LIVING TABLE (generated by BalanceReport)");
        System.out.println(" Reference player DPT = " + BalanceConfig.REFERENCE_PLAYER_DPT
                + "   eHP = " + BalanceConfig.REFERENCE_PLAYER_EHP
                + "   ammoEff anchor = " + BalanceConfig.REFERENCE_AMMO_EFFICIENCY);
        System.out.println("====================================================================================");
    }

    // -----------------------------------------------------------------------------------
    // WEAPONS — sustained DPT, ammo efficiency, power score vs role band.
    // -----------------------------------------------------------------------------------
    private static void printWeaponTable() {
        System.out.println("WEAPONS");
        System.out.printf("%-16s %-10s %8s %8s %10s %12s %-6s%n",
                "weapon", "role", "sustDPT", "ammoEff", "powerScore", "band", "in?");
        System.out.println("------------------------------------------------------------------------------------");

        printWeaponRow("Shotgun",        WeaponRole.BURST,
                BalanceConfig.SHOTGUN_CLIP_SIZE,     BalanceConfig.SHOTGUN_DAMAGE,     BalanceConfig.SHOTGUN_RELOAD_TIME_TICKS,  1);
        printWeaponRow("Dbl Shotgun",    WeaponRole.BURST,
                BalanceConfig.DBL_SHOTGUN_CLIP_SIZE, BalanceConfig.DBL_SHOTGUN_DAMAGE, BalanceConfig.DBL_SHOTGUN_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Plasma Rifle",   WeaponRole.BURST,
                BalanceConfig.PLASMA_RIFLE_CLIP_SIZE, BalanceConfig.PLASMA_RIFLE_DAMAGE, BalanceConfig.PLASMA_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Assault Rifle",  WeaponRole.WORKHORSE,
                BalanceConfig.ASSAULT_RIFLE_CLIP_SIZE, BalanceConfig.ASSAULT_RIFLE_DAMAGE, BalanceConfig.ASSAULT_RIFLE_RELOAD_TIME_TICKS, 1);
        printWeaponRow("Chaingun",       WeaponRole.WORKHORSE,
                BalanceConfig.CHAINGUN_CLIP_SIZE, BalanceConfig.CHAINGUN_DAMAGE, BalanceConfig.CHAINGUN_RELOAD_TIME_TICKS, 1);
        // Railgun scored at FULL charge (its intended engagement state).
        printWeaponRow("Railgun(full)",  WeaponRole.HEAVY,
                BalanceConfig.RAILGUN_CLIP_SIZE,
                BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE[BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE.length - 1],
                BalanceConfig.RAILGUN_RELOAD_TIME_TICKS, 1);
        // Grenade scored on its centre splash damage.
        printWeaponRow("Grenade Lchr",   WeaponRole.HEAVY,
                BalanceConfig.GRENADE_CLIP_SIZE, BalanceConfig.GRENADE_SPLASH_DAMAGE, BalanceConfig.GRENADE_RELOAD_TIME_TICKS, 1);
    }

    private static void printWeaponRow(String weaponName, WeaponRole weaponRole,
                                       int clipSize, int damagePerShot, int reloadTicks, int ammoPerShot) {
        float sustainedDamagePerTurn = GameMath.sustainedDamagePerTurn(clipSize, damagePerShot, reloadTicks);
        float ammoEfficiency = GameMath.ammoEfficiency(damagePerShot, ammoPerShot);
        float ammoEfficiencyNormalized = ammoEfficiency / BalanceConfig.REFERENCE_AMMO_EFFICIENCY;
        float powerScore = GameMath.weaponPowerScore(sustainedDamagePerTurn, ammoEfficiencyNormalized);

        boolean insideBand = powerScore >= weaponRole.bandMinimum && powerScore <= weaponRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", weaponRole.bandMinimum, weaponRole.bandMaximum);

        System.out.printf("%-16s %-10s %8.1f %8.1f %10.1f %12s %-6s%n",
                weaponName, weaponRole.name(), sustainedDamagePerTurn, ammoEfficiency,
                powerScore, bandText, bandVerdict(insideBand, powerScore, weaponRole.bandMinimum));
    }

    // -----------------------------------------------------------------------------------
    // ENEMIES — threat points vs role band, plus the golden-ratio (TTD/TTK) sanity check.
    // Golden ratio uses the player's best burst (shotgun) for TTK and reference eHP for TTD.
    // -----------------------------------------------------------------------------------
    private static void printEnemyTable() {
        System.out.println("ENEMIES");
        System.out.printf("%-16s %-11s %5s %6s %5s %8s %10s %-6s %9s %-6s%n",
                "enemy", "role", "eHP", "atkDmg", "cad", "posMult", "TP", "in?", "TTD/TTK", "gr?");
        System.out.println("------------------------------------------------------------------------------------");

        // cadence: ranged enemies attack every turn (1); melee enemies attack on their move cadence.
        printEnemyRow("Gore Biter",  EnemyRole.CHAFF,   BalanceConfig.GORE_BITER_MAX_HEALTH,
                BalanceConfig.GORE_BITER_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Eye Tyrant",  EnemyRole.CHAFF,   BalanceConfig.EYE_TYRANT_MAX_HEALTH,
                BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Acid Drone",  EnemyRole.SOLDIER, BalanceConfig.ACID_DRONE_MAX_HEALTH,
                BalanceConfig.ACID_DRONE_ATTACK_DAMAGE,  1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Void Shroud", EnemyRole.SOLDIER, BalanceConfig.VOID_SHROUD_MAX_HEALTH,
                BalanceConfig.VOID_SHROUD_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, false);
        printEnemyRow("Mire Wraith", EnemyRole.SOLDIER, BalanceConfig.MIRE_WRAITH_MAX_HEALTH,
                BalanceConfig.MIRE_WRAITH_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_RANGED,     false);
        printEnemyRow("Shell Brute", EnemyRole.BRUISER, BalanceConfig.SHELL_BRUTE_MAX_HEALTH,
                BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_MELEE,      true);
        printEnemyRow("Plague Hulk", EnemyRole.SOLDIER, BalanceConfig.PLAGUE_HULK_MAX_HEALTH,
                BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE, BalanceConfig.PLAGUE_HULK_MOVE_EVERY_N_TURNS,
                BalanceConfig.POSITIONAL_MULT_MELEE,      false);
        // Iron Stalker scored on its melee profile (its higher damage line), like the contract worked example.
        printEnemyRow("Iron Stalker", EnemyRole.MINI_ELITE, BalanceConfig.IRON_STALKER_MAX_HEALTH,
                BalanceConfig.IRON_STALKER_MELEE_DAMAGE, 1, BalanceConfig.POSITIONAL_MULT_FAST_MELEE, true);
    }

    private static void printEnemyRow(String enemyName, EnemyRole enemyRole, int rawHealth,
                                      int attackDamage, int attackCadenceTurns,
                                      float positionalMultiplier, boolean useBruiserGoldenBand) {
        // Enemies currently have no dodge or flat reduction, so eHP == raw HP.
        float enemyEffectiveHitPoints = GameMath.effectiveHitPoints(rawHealth, 0f, 0f, 0f, 0f);
        float threatPoints = GameMath.threatPoints(attackDamage, attackCadenceTurns,
                enemyEffectiveHitPoints, BalanceConfig.REFERENCE_PLAYER_DPT, positionalMultiplier);
        boolean insideBand = threatPoints >= enemyRole.bandMinimum && threatPoints <= enemyRole.bandMaximum;
        String bandText = String.format("%.0f-%.0f", enemyRole.bandMinimum, enemyRole.bandMaximum);

        // Golden ratio: TTK by the player's best burst (shotgun), TTD by enemy DPT into reference eHP.
        int turnsToKill = GameMath.turnsToKill(enemyEffectiveHitPoints, BalanceConfig.SHOTGUN_DAMAGE);
        float enemyDamagePerTurn = (float) attackDamage / Math.max(1, attackCadenceTurns);
        int turnsToDie = GameMath.turnsToKill(BalanceConfig.REFERENCE_PLAYER_EHP, enemyDamagePerTurn);
        float goldenRatio = GameMath.goldenRatio(turnsToDie, turnsToKill);

        float goldenMinimum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MIN : BalanceConfig.GOLDEN_RATIO_TRASH_MIN;
        float goldenMaximum = useBruiserGoldenBand ? BalanceConfig.GOLDEN_RATIO_BRUISER_MAX : BalanceConfig.GOLDEN_RATIO_TRASH_MAX;
        boolean goldenInside = goldenRatio >= goldenMinimum && goldenRatio <= goldenMaximum;

        System.out.printf("%-16s %-11s %5.0f %6d %5d %8.2f %10.1f %-6s %9.1f %-6s%n",
                enemyName, enemyRole.name(), enemyEffectiveHitPoints, attackDamage, attackCadenceTurns,
                positionalMultiplier, threatPoints, bandVerdict(insideBand, threatPoints, enemyRole.bandMinimum),
                goldenRatio, bandVerdict(goldenInside, goldenRatio, goldenMinimum));
    }

    private static String bandVerdict(boolean insideBand, float value, float bandMinimum) {
        if (insideBand) {
            return "OK";
        }
        return value < bandMinimum ? "UNDER" : "OVER";
    }

    // -----------------------------------------------------------------------------------
    // SCARCITY — the model floor's SUPPLY vs DEMAND, scarcity ratio S, per-weapon S,
    // reserve banking ceiling, and the heal economy's net HP drain (idea 3).
    // Every number is computed from BalanceConfig through GameMath, so it cannot drift.
    // -----------------------------------------------------------------------------------
    private static void printScarcityTable() {
        // DEMAND = sum of every model-floor enemy's eHP (eHP == raw HP: no dodge/reduction).
        float demand =
                  BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT  * enemyEffectiveHitPoints(BalanceConfig.GORE_BITER_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT  * enemyEffectiveHitPoints(BalanceConfig.EYE_TYRANT_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT * enemyEffectiveHitPoints(BalanceConfig.SHELL_BRUTE_MAX_HEALTH)
                + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT * enemyEffectiveHitPoints(BalanceConfig.PLAGUE_HULK_MAX_HEALTH);
        int enemyCount = BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT;

        // Expected ammo boxes per floor, split uniformly across the 5 floor-droppable types
        // (matches the generator's randomAmmoChar() uniform roll).
        float expectedBoxes = GameMath.expectedAmmoBoxesPerFloor(
                BalanceConfig.MODEL_FLOOR_ROOM_COUNT, BalanceConfig.LEVEL_GEN_AMMO_CHANCE_PER_ROOM,
                enemyCount, BalanceConfig.ENEMY_AMMO_DROP_CHANCE);
        float boxesPerType = expectedBoxes / BalanceConfig.MODEL_FLOOR_AMMO_TYPE_COUNT;

        System.out.println("SCARCITY — model floor (depth 1): " + enemyCount + " enemies, "
                + BalanceConfig.MODEL_FLOOR_ROOM_COUNT + " rooms, DEMAND=" + String.format("%.0f", demand)
                + " dmg ; expected ammo boxes/floor=" + String.format("%.2f", expectedBoxes)
                + " (" + String.format("%.2f", boxesPerType) + "/type)");
        System.out.printf("%-10s %7s %9s %8s %10s %-7s %12s%n",
                "ammoType", "boxSize", "dmg/unit", "supply", "perWpnS", "<0.6?", "bankFloors");
        System.out.println("------------------------------------------------------------------------------------");

        // Representative damage-per-unit = the per-shot damage of the weapon that eats this
        // ammo (one shot costs one unit), so supply = boxes * boxSize * damagePerShot.
        float railgunFull = BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE[BalanceConfig.RAILGUN_DAMAGE_BY_CHARGE.length - 1];
        float bulletsSupply = printScarcityRow("Bullets", boxesPerType, BalanceConfig.AMMO_BOX_BULLETS,
                BalanceConfig.ASSAULT_RIFLE_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_BULLETS, demand);
        float shellsSupply  = printScarcityRow("Shells",  boxesPerType, BalanceConfig.AMMO_BOX_SHELLS,
                BalanceConfig.SHOTGUN_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_SHELLS, demand);
        float cellsSupply   = printScarcityRow("Cells",   boxesPerType, BalanceConfig.AMMO_BOX_CELLS,
                BalanceConfig.PLASMA_RIFLE_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_CELLS, demand);
        float rocketsSupply = printScarcityRow("Rockets", boxesPerType, BalanceConfig.AMMO_BOX_ROCKETS,
                BalanceConfig.GRENADE_SPLASH_DAMAGE, BalanceConfig.AMMO_RESERVE_CAP_ROCKETS, demand);
        float slugsSupply   = printScarcityRow("Slugs",   boxesPerType, BalanceConfig.RAILGUN_PICKUP_SLUGS,
                railgunFull, BalanceConfig.RAILGUN_MAX_SLUGS, demand);

        float totalSupply = bulletsSupply + shellsSupply + cellsSupply + rocketsSupply + slugsSupply;
        float scarcityRatio = GameMath.scarcityRatio(totalSupply, demand);
        boolean ratioInBand = scarcityRatio >= BalanceConfig.SCARCITY_RATIO_FLOOR_MIN
                && scarcityRatio <= BalanceConfig.SCARCITY_RATIO_FLOOR_MAX;
        System.out.println("------------------------------------------------------------------------------------");
        System.out.printf("FLOOR-WIDE  SUPPLY=%.0f  DEMAND=%.0f  S=%.2f  band=%.2f-%.2f  %s%n",
                totalSupply, demand, scarcityRatio,
                BalanceConfig.SCARCITY_RATIO_FLOOR_MIN, BalanceConfig.SCARCITY_RATIO_FLOOR_MAX,
                bandVerdict(ratioInBand, scarcityRatio, BalanceConfig.SCARCITY_RATIO_FLOOR_MIN));

        printHealEconomy(demand, enemyCount);
    }

    /** Prints one ammo-type row and returns that type's supply damage. */
    private static float printScarcityRow(String ammoType, float boxesPerType, int boxSize,
                                          float damagePerUnit, int reserveCap, float demand) {
        float supply = GameMath.ammoSupplyDamage(boxesPerType, boxSize, damagePerUnit);
        float perWeaponShare = GameMath.scarcityRatio(supply, demand);
        boolean underCap = perWeaponShare < BalanceConfig.SCARCITY_PER_WEAPON_MAX;
        float bankFloors = GameMath.reserveBankingFloors(reserveCap, damagePerUnit, demand);
        System.out.printf("%-10s %7d %9.0f %8.0f %10.2f %-7s %12.2f%n",
                ammoType, boxSize, damagePerUnit, supply, perWeaponShare,
                underCap ? "OK" : "OVER", bankFloors);
        return supply;
    }

    /** Prints the heal economy: incoming damage, heal supply, and net HP drain vs band. */
    private static void printHealEconomy(float demand, int enemyCount) {
        // Total enemy damage-per-turn across the model floor (melee cadence folded in).
        float totalEnemyDamagePerTurn =
                  BalanceConfig.MODEL_FLOOR_GORE_BITER_COUNT  * (BalanceConfig.GORE_BITER_ATTACK_DAMAGE  / 1f)
                + BalanceConfig.MODEL_FLOOR_EYE_TYRANT_COUNT  * (BalanceConfig.EYE_TYRANT_ATTACK_DAMAGE  / 1f)
                + BalanceConfig.MODEL_FLOOR_SHELL_BRUTE_COUNT * (BalanceConfig.SHELL_BRUTE_ATTACK_DAMAGE / 1f)
                + BalanceConfig.MODEL_FLOOR_PLAGUE_HULK_COUNT
                        * (BalanceConfig.PLAGUE_HULK_ATTACK_DAMAGE / (float) BalanceConfig.PLAGUE_HULK_MOVE_EVERY_N_TURNS);

        float incoming = GameMath.incomingDamagePerFloor(totalEnemyDamagePerTurn,
                BalanceConfig.MODEL_FLOOR_TURNS_ENGAGED_PER_ENEMY, BalanceConfig.MODEL_FLOOR_AVOIDANCE_FACTOR);

        float averageMedkitHeal = (BalanceConfig.MEDKIT_STIM_HEAL + BalanceConfig.MEDKIT_FULL_HEAL) / 2f;
        float averageArmourValue = (BalanceConfig.ARMOUR_SHARD_VALUE + BalanceConfig.ARMOUR_VEST_VALUE) / 2f;
        float healSupply = GameMath.healSupplyPerFloor(BalanceConfig.MODEL_FLOOR_EXPECTED_MEDKITS, averageMedkitHeal,
                BalanceConfig.MODEL_FLOOR_EXPECTED_ARMOUR_PICKUPS, averageArmourValue);

        float netDrain = GameMath.netHpDrainPerFloor(incoming, healSupply);
        float drainFraction = netDrain / BalanceConfig.REFERENCE_PLAYER_EHP;
        boolean drainInBand = drainFraction >= BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN
                && drainFraction <= BalanceConfig.HEAL_NET_DRAIN_FRACTION_MAX;

        // Informational: what a full medkit buys, in survival turns, at the floor's average rate.
        int floorEngagementTurns = Math.max(1, enemyCount * BalanceConfig.MODEL_FLOOR_TURNS_ENGAGED_PER_ENEMY);
        float averageIncomingDamagePerTurn = incoming / floorEngagementTurns;
        float fullMedkitTurns = GameMath.survivalTurnsBought(BalanceConfig.MEDKIT_FULL_HEAL, averageIncomingDamagePerTurn);

        System.out.println();
        System.out.println("HEAL ECONOMY — model floor");
        System.out.printf("  INCOMING=%.0f  HEAL_SUPPLY=%.0f  netHpDrain=%.0f  (%.1f%% of %.0f eHP ; band %.0f-%.0f%%)  %s%n",
                incoming, healSupply, netDrain, drainFraction * 100f, BalanceConfig.REFERENCE_PLAYER_EHP,
                BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN * 100f, BalanceConfig.HEAL_NET_DRAIN_FRACTION_MAX * 100f,
                bandVerdict(drainInBand, drainFraction, BalanceConfig.HEAL_NET_DRAIN_FRACTION_MIN));
        System.out.printf("  full medkit (%d HP) buys %.1f survival-turns at %.1f avg incoming dmg/turn (informational)%n",
                BalanceConfig.MEDKIT_FULL_HEAL, fullMedkitTurns, averageIncomingDamagePerTurn);
    }

    /** Enemy eHP with no dodge or flat reduction (the contract rule for current enemies). */
    private static float enemyEffectiveHitPoints(int rawHealth) {
        return GameMath.effectiveHitPoints(rawHealth, 0f, 0f, 0f, 0f);
    }

    private static void printLegend() {
        System.out.println("LEGEND: in?/gr?/<0.6?/band = OK inside band, UNDER below, OVER above.");
        System.out.println("  sustDPT = (clip*dmg)/(clip+reload).  powerScore = sustDPT*sqrt(ammoEff/anchor).");
        System.out.println("  TP = (atkDmg/cadence) * (eHP/refDPT) * posMult.  TTD/TTK = golden ratio.");
        System.out.println("  S = SUPPLY/DEMAND (ranged ammo vs sum of enemy eHP).  perWpnS = that weapon's share.");
        System.out.println("  bankFloors = full reserve / floor demand (anti-hoard target ~"
                + BalanceConfig.RESERVE_BANKING_FLOORS_TARGET + ").  netHpDrain = INCOMING - HEAL_SUPPLY.");
        System.out.println("Out-of-band rows are tuning targets — see docs/balance-rule-system.txt.");
    }
}
